### ISSUE TITLE
`Documentation HTML` in README is not pointing to any valid doc.

### ISSUE THREAD

**Issue by jens1o** [dm-drogeriemarkt/activedirectory-spring-boot-starter#2]
I literally just see the sourcecode of it. Perhaps it is possible to let the browser render the actual document? 👍

**Comment by fabianbuch** [comment]
Thanks for pointing this out. Without rewriting the asciidoc documentation in markdown I didn't find a quick solution to generate HTML that is rendered nicely by github (without github pages). Instead with dd817afd0fe31a44b2b96da56ee7667c5ae1dc02 I generate PDF documentation which is now referenced in the README.md.
